package com.youngcha.ohmycarset.util

const val MILLISECONDS_PER_INCH = 150f
const val OPTION_SELECTION = "옵션 선택"

const val CREAMY_WHITE_PEARL_NAME = "크리미 화이트 펄"
const val ABYSS_BLACK_PEARL_NAME = "어비스 블랙펄"
const val SHIMMERING_SILVER_METALLIC_NAME = "쉬머링 실버 메탈릭"
const val LAPIRITE_GRAY_METALLIC_NAME = "라파이트 그레이 메탈릭"
const val GAIA_BROWN_PEARL_NAME = "가이아 브라운 펄"
const val MOONLIGHT_BLUE_PEARL_NAME = "문라이트 블루 펄"

const val CREAMY_WHITE_PEARL_CODE = "WC9"
const val ABYSS_BLACK_PEARL_CODE = "A2B"
const val SHIMMERING_SILVER_METALLIC_CODE = "R2T"
const val LAPIRITE_GRAY_METALLIC_CODE = "P7V"
const val GAIA_BROWN_PEARL_CODE = "D2S"
const val MOONLIGHT_BLUE_PEARL_CODE = "UB7"

val COLOR_NAME_TO_CODE_MAP = mapOf(
    CREAMY_WHITE_PEARL_NAME to CREAMY_WHITE_PEARL_CODE,
    ABYSS_BLACK_PEARL_NAME to ABYSS_BLACK_PEARL_CODE,
    SHIMMERING_SILVER_METALLIC_NAME to SHIMMERING_SILVER_METALLIC_CODE,
    LAPIRITE_GRAY_METALLIC_NAME to LAPIRITE_GRAY_METALLIC_CODE,
    GAIA_BROWN_PEARL_NAME to GAIA_BROWN_PEARL_CODE,
    MOONLIGHT_BLUE_PEARL_NAME to MOONLIGHT_BLUE_PEARL_CODE
)

fun getColorCodeFromName(colorName: String): String? {
    return COLOR_NAME_TO_CODE_MAP[colorName]
}
